[tool.pyright]
typeCheckingMode = "strict"

[tool.black]
line-length = 240                # 88
skip-string-normalization = true
# target-version = ["py38"] # seems to fail on match statements
include = '\.pyi?$'
exclude = '''
/(
  | \.git
  | __pycache__
  | build
  | \.tox
  | \.pytest_cache
)/
'''

[tool.isort]
profile = "black"
line_length = 88
# py_version = "38"
lines_after_imports = 2
skip = [".git", "__pycache__", "build", ".tox", ".pytest_cache"]
