[tool.pyright]
typeCheckingMode = "strict"

[tool.black]
line-length = 180                # 79 | 88 | 99
skip-string-normalization = true
# target-version = ["py38"] # seems to fail on match statements
include = '\.pyi?$'
exclude = '''
/(
  | \.git
  | __pycache__
  | archive
  | build
  | docs
  | \.tox
  | \.pytest_cache
)/
'''

[tool.isort]
profile = "black"
line_length = 72
# py_version = "38"
lines_after_imports = 2
skip = [
  ".git",
  "__pycache__",
  "archive",
  "build",
  "docs",
  ".tox",
  ".pytest_cache",
]
