[tool.pyright]
typeCheckingMode = "strict"

# This is moved to ./.flake8
# [tool.flake8]
# ignore = E501 W503 W504 E203
# max-line-length = 200
# max-complexity = 10

[tool.black]
line-length = 200                # 79 | 88 | 99
skip-string-normalization = true
# target-version = ["py38"] # seems to fail on match statements
include = '\.pyi?$'
exclude = '''
/(
  | \.git
  | __pycache__
  | archive
  | build
  | docs
  | \.tox
  | \.pytest_cache
)/
'''

[tool.isort]
profile = "black"
line_length = 72
# py_version = "38"
lines_after_imports = 2
skip = [
  ".git",
  "__pycache__",
  "archive",
  "build",
  "docs",
  ".tox",
  ".pytest_cache",
]

