# config.toml

# Game Window Configuration
[game.general.window]
width = 640  # Width of the game window
height = 480 # Height of the game window

# Player Entity Configuration
[game.entity.player.movement]
dash = 8  # Dash distance
jump = 3  # Jump height
speed = 5 # Movement speed

# Enemy Entity Configuration
[game.entity.enemy.movement]
jump = 3  # Jump height
speed = 5 # Movement speed

[game.world.stars]
count = 32 # 16 <= count <= 64

# Miscellaneous Decorations
[game.misc.decorations]
drop_shadow = true     # Apply drop shadow effect
shadow_range = 1       # Offset in all directions for shadow
col_shadow = [0, 0, 0] # RGB color of the shadow (black)

# Blur Effect Configuration
[game.misc.decorations.blur]
enabled = false   # Enable/disable blur effect
size = 3          # Size of the blur
passes = 1        # Number of passes for the blur effect
vibrancy = 0.1696 # Vibrancy level of the blur

[sound.volume]
# TODO:
